
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea1.Visual;

/**
 *
 * @author josue
 */
public class InformeJFrame extends javax.swing.JFrame {
    
    float dolaresComprados;
    float dolaresVendidos;
    /**
     * Creates new form InformeJFrame
     * @param dolaresComprados
     * @param dolaresVendidos
     */
    public InformeJFrame(float dolaresComprados, float dolaresVendidos) {
        initComponents();
        this.dolaresComprados = dolaresComprados;
        this.dolaresVendidos = dolaresVendidos;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        dolaresCompradosLabel = new javax.swing.JLabel();
        dolaresVendidosjLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Informe de compra y venta de dolares");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dolaresCompradosLabel.setText("Dolares comprado");

        dolaresVendidosjLabel.setText("Dolares Vendidos");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setText("Informe de la sesión:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dolaresCompradosLabel)
                            .addComponent(dolaresVendidosjLabel))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(dolaresCompradosLabel)
                .addGap(51, 51, 51)
                .addComponent(dolaresVendidosjLabel)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Muestra los datos de los dolares comprados y vendidos al finalizar la calculadora.
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dolaresCompradosLabel.setText("Se compraron " + dolaresComprados +" dolares");
        dolaresVendidosjLabel.setText("Se vendieron " + dolaresVendidos + " dolares");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dolaresCompradosLabel;
    private javax.swing.JLabel dolaresVendidosjLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
