/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea1.Visual;

import tarea1.Visual.MoneyExchangeJFrame;
import tarea1.Visual.AgregarEditarMonedasJFrame;
import tarea1.Visual.AgregarEditarClientesJFrame;
import sun.management.Agent;
import tarea1.Conversion_Nueva;
import tarea1.Equivalencias_Nuevas;

/**
 *
 * @author josue
 */
public class MenuJframe extends javax.swing.JFrame {
    private Conversion_Nueva convercion;
    private Equivalencias_Nuevas equivalencia;
    private MoneyExchangeJFrame moneyExchange;
    private AgregarEditarMonedasJFrame monedas;
    private AgregarEditarClientesJFrame clientes;
    private ReportePorCliente reporteCliente;
    private ReportePorMonedas reporteMoneda;

    /**
     * Creates new form MenuJframe
     */
    public MenuJframe() {
        initComponents();
        this.equivalencia = new Equivalencias_Nuevas(17);
        this.convercion = new Conversion_Nueva(this.getEquivalencia());
        this.monedas = new AgregarEditarMonedasJFrame(this.convercion, this.getEquivalencia());
        this.moneyExchange = new MoneyExchangeJFrame(this.convercion, this.getEquivalencia()); 
        this.moneyExchange.setMenu(this);
        this.clientes = new AgregarEditarClientesJFrame(this.convercion, this.getEquivalencia());  
        this.clientes.setMenu(this);
        this.reporteCliente =  new ReportePorCliente();
        this.reporteMoneda =  new ReportePorMonedas();
        reporteMoneda.setMenu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenidojLabel1 = new javax.swing.JLabel();
        convertirjButton1 = new javax.swing.JButton();
        agregarEditarMonedasjButton2 = new javax.swing.JButton();
        agregarEditarClientesjButton = new javax.swing.JButton();
        reporteClientejButton = new javax.swing.JButton();
        reportePorMonedajButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu CRUnion");

        bienvenidojLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidojLabel1.setText("Bienvenido al conversor");

        convertirjButton1.setText("Convertir");
        convertirjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirjButton1ActionPerformed(evt);
            }
        });

        agregarEditarMonedasjButton2.setText("Agregar o editar monedas");
        agregarEditarMonedasjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEditarMonedasjButton2ActionPerformed(evt);
            }
        });

        agregarEditarClientesjButton.setText("Agregar o editar clientes");
        agregarEditarClientesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEditarClientesjButtonActionPerformed(evt);
            }
        });

        reporteClientejButton.setText("Reporte por Cliente");
        reporteClientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteClientejButtonActionPerformed(evt);
            }
        });

        reportePorMonedajButton.setText("Reporte por moneda");
        reportePorMonedajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePorMonedajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(agregarEditarMonedasjButton2)
                    .addComponent(convertirjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bienvenidojLabel1)
                    .addComponent(agregarEditarClientesjButton)
                    .addComponent(reporteClientejButton)
                    .addComponent(reportePorMonedajButton))
                .addGap(96, 96, 96))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agregarEditarClientesjButton, agregarEditarMonedasjButton2, bienvenidojLabel1, convertirjButton1, reporteClientejButton, reportePorMonedajButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bienvenidojLabel1)
                .addGap(26, 26, 26)
                .addComponent(convertirjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(agregarEditarMonedasjButton2)
                .addGap(35, 35, 35)
                .addComponent(agregarEditarClientesjButton)
                .addGap(38, 38, 38)
                .addComponent(reporteClientejButton)
                .addGap(37, 37, 37)
                .addComponent(reportePorMonedajButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agregarEditarClientesjButton, agregarEditarMonedasjButton2, bienvenidojLabel1, convertirjButton1, reporteClientejButton, reportePorMonedajButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
    
    private void convertirjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirjButton1ActionPerformed
        //Realiza la accion de abrir la ventana de convercion
        moneyExchange.setVisible(true);
        
    }//GEN-LAST:event_convertirjButton1ActionPerformed

    private void agregarEditarMonedasjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEditarMonedasjButton2ActionPerformed
        //Realiza la accion de mostrar la ventana de agregar y editar divisas
        monedas.setVisible(true);
    }//GEN-LAST:event_agregarEditarMonedasjButton2ActionPerformed

    private void agregarEditarClientesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEditarClientesjButtonActionPerformed
        getClientes().setVisible(true);       
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarEditarClientesjButtonActionPerformed

    private void reportePorMonedajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePorMonedajButtonActionPerformed
        getReporteMoneda().setVisible(true);  
    }//GEN-LAST:event_reportePorMonedajButtonActionPerformed

    private void reporteClientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteClientejButtonActionPerformed
        getReporteCliente().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_reporteClientejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEditarClientesjButton;
    private javax.swing.JButton agregarEditarMonedasjButton2;
    private javax.swing.JLabel bienvenidojLabel1;
    private javax.swing.JButton convertirjButton1;
    private javax.swing.JButton reporteClientejButton;
    private javax.swing.JButton reportePorMonedajButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the clientes
     */
    public AgregarEditarClientesJFrame getClientes() {
        return clientes;
    }

    /**
     * @return the reporteCliente
     */
    public ReportePorCliente getReporteCliente() {
        return reporteCliente;
    }

    /**
     * @return the reporteMoneda
     */
    public ReportePorMonedas getReporteMoneda() {
        return reporteMoneda;
    }

    /**
     * @return the equivalencia
     */
    public Equivalencias_Nuevas getEquivalencia() {
        return equivalencia;
    }
}
